runtime: nodejs16
env_variables:
  PROJECT_ID: 'peaceful-rex-368804'
  CLIENT_ID: '1059219973799-bumnu077tfd52kdolsicl1prbc7b3bkp.apps.googleusercontent.com'
  CLIENT_SECRET: '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'